/*
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AuthDTO;
import org.openapitools.client.model.ImportClientsDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseApi
 */
@Disabled
public class EnterpriseApiTest {

    private final EnterpriseApi api = new EnterpriseApi();

    /**
     * Authenticate and retrieve OAuth2 token
     *
     * Exchanges your enterprise client credentials for an OAuth2 access token. This token is required for accessing protected enterprise endpoints including import-clients and document operations. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enterpriseControllerAuthTest() throws ApiException {
        AuthDTO authDTO = null;
        Object response = api.enterpriseControllerAuth(authDTO);
        // TODO: test validations
    }

    /**
     * Import enterprise clients
     *
     * Imports a list of clients into your organization. Requires a valid OAuth2 access token obtained from the /auth endpoint. Each client will be added to your organization with the provided email and unique external client ID.  The clientId will serve as an external identifier to track which enterprise client each consumer belongs to. Critically, this clientId mapping determines document upload behavior: documents uploaded by imported clients will be stored unencrypted (enterprise-managed storage). Clients will be created in Cognito if they do not already exist, and their association with your organization and the provided clientId will be stored in the system.  Import Format: A customer-generated CSV file will be used to onboard multiple users in bulk. The CSV file will have the following format:  clientEmail,clientId  When using the Brands App, the user&#39;s email will be used as the clientEmail and the initial password will be an OTP sent to the user&#39;s email. The clientId will be any unique identifier from your enterprise system that you want to associate with this client. This will allow you to maintain a mapping between your enterprise system and the consumers created in this platform, and will enable unencrypted document storage for these clients.  
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enterpriseControllerImportClientsTest() throws ApiException {
        ImportClientsDTO importClientsDTO = null;
        Object response = api.enterpriseControllerImportClients(importClientsDTO);
        // TODO: test validations
    }

}
