/*
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AuthDTO;
import org.openapitools.client.model.ImportClientsDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseApi
 */
@Disabled
public class EnterpriseApiTest {

    private final EnterpriseApi api = new EnterpriseApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enterpriseControllerAuthTest() throws ApiException {
        AuthDTO authDTO = null;
        Object response = api.enterpriseControllerAuth(authDTO);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enterpriseControllerImportClientsTest() throws ApiException {
        ImportClientsDTO importClientsDTO = null;
        Object response = api.enterpriseControllerImportClients(importClientsDTO);
        // TODO: test validations
    }

}
