# coding: utf-8

"""
    Futr Enterprise API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_client_dto import ImportClientDTO

class TestImportClientDTO(unittest.TestCase):
    """ImportClientDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportClientDTO:
        """Test ImportClientDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportClientDTO`
        """
        model = ImportClientDTO()
        if include_optional:
            return ImportClientDTO(
                client_email = '',
                client_id = ''
            )
        else:
            return ImportClientDTO(
                client_email = '',
                client_id = '',
        )
        """

    def testImportClientDTO(self):
        """Test ImportClientDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
