# coding: utf-8

"""
    Futr Enterprise API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_clients_dto import ImportClientsDTO

class TestImportClientsDTO(unittest.TestCase):
    """ImportClientsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportClientsDTO:
        """Test ImportClientsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportClientsDTO`
        """
        model = ImportClientsDTO()
        if include_optional:
            return ImportClientsDTO(
                clients = [
                    openapi_client.models.import_client_dto.ImportClientDTO(
                        client_email = '', 
                        client_id = '', )
                    ]
            )
        else:
            return ImportClientsDTO(
                clients = [
                    openapi_client.models.import_client_dto.ImportClientDTO(
                        client_email = '', 
                        client_id = '', )
                    ],
        )
        """

    def testImportClientsDTO(self):
        """Test ImportClientsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
