# coding: utf-8

"""
    Futr Enterprise API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.enterprise_api import EnterpriseApi


class TestEnterpriseApi(unittest.TestCase):
    """EnterpriseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnterpriseApi()

    def tearDown(self) -> None:
        pass

    def test_enterprise_controller_auth(self) -> None:
        """Test case for enterprise_controller_auth

        """
        pass


if __name__ == '__main__':
    unittest.main()
