/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface DocumentControllerUploadDocumentRequest {
    file: Blob;
    monetized: boolean;
    fileHash: string;
    derivedKey?: string;
    password?: string;
    isID?: boolean;
    taskId?: string;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for documentControllerUploadDocument without sending the request
     */
    async documentControllerUploadDocumentRequestOpts(requestParameters: DocumentControllerUploadDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling documentControllerUploadDocument().'
            );
        }

        if (requestParameters['monetized'] == null) {
            throw new runtime.RequiredError(
                'monetized',
                'Required parameter "monetized" was null or undefined when calling documentControllerUploadDocument().'
            );
        }

        if (requestParameters['fileHash'] == null) {
            throw new runtime.RequiredError(
                'fileHash',
                'Required parameter "fileHash" was null or undefined when calling documentControllerUploadDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['monetized'] != null) {
            formParams.append('monetized', requestParameters['monetized'] as any);
        }

        if (requestParameters['fileHash'] != null) {
            formParams.append('fileHash', requestParameters['fileHash'] as any);
        }

        if (requestParameters['derivedKey'] != null) {
            formParams.append('derivedKey', requestParameters['derivedKey'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['isID'] != null) {
            formParams.append('isID', requestParameters['isID'] as any);
        }

        if (requestParameters['taskId'] != null) {
            formParams.append('taskId', requestParameters['taskId'] as any);
        }


        let urlPath = `/documents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Uploading a new document
     */
    async documentControllerUploadDocumentRaw(requestParameters: DocumentControllerUploadDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.documentControllerUploadDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Uploading a new document
     */
    async documentControllerUploadDocument(requestParameters: DocumentControllerUploadDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.documentControllerUploadDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
