/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthDTO,
} from '../models/index';
import {
    AuthDTOFromJSON,
    AuthDTOToJSON,
} from '../models/index';

export interface EnterpriseControllerAuthRequest {
    authDTO: AuthDTO;
}

/**
 * 
 */
export class EnterpriseApi extends runtime.BaseAPI {

    /**
     * Creates request options for enterpriseControllerAuth without sending the request
     */
    async enterpriseControllerAuthRequestOpts(requestParameters: EnterpriseControllerAuthRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authDTO'] == null) {
            throw new runtime.RequiredError(
                'authDTO',
                'Required parameter "authDTO" was null or undefined when calling enterpriseControllerAuth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/enterprise/auth`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthDTOToJSON(requestParameters['authDTO']),
        };
    }

    /**
     */
    async enterpriseControllerAuthRaw(requestParameters: EnterpriseControllerAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.enterpriseControllerAuthRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async enterpriseControllerAuth(requestParameters: EnterpriseControllerAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.enterpriseControllerAuthRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
