/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthDTO
 */
export interface AuthDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthDTO
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDTO
     */
    clientSecret: string;
}

/**
 * Check if a given object implements the AuthDTO interface.
 */
export function instanceOfAuthDTO(value: object): value is AuthDTO {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    return true;
}

export function AuthDTOFromJSON(json: any): AuthDTO {
    return AuthDTOFromJSONTyped(json, false);
}

export function AuthDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'clientSecret': json['clientSecret'],
    };
}

export function AuthDTOToJSON(json: any): AuthDTO {
    return AuthDTOToJSONTyped(json, false);
}

export function AuthDTOToJSONTyped(value?: AuthDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
    };
}

