/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportClientDTO } from './ImportClientDTO';
import {
    ImportClientDTOFromJSON,
    ImportClientDTOFromJSONTyped,
    ImportClientDTOToJSON,
    ImportClientDTOToJSONTyped,
} from './ImportClientDTO';

/**
 * 
 * @export
 * @interface ImportClientsDTO
 */
export interface ImportClientsDTO {
    /**
     * 
     * @type {Array<ImportClientDTO>}
     * @memberof ImportClientsDTO
     */
    clients: Array<ImportClientDTO>;
}

/**
 * Check if a given object implements the ImportClientsDTO interface.
 */
export function instanceOfImportClientsDTO(value: object): value is ImportClientsDTO {
    if (!('clients' in value) || value['clients'] === undefined) return false;
    return true;
}

export function ImportClientsDTOFromJSON(json: any): ImportClientsDTO {
    return ImportClientsDTOFromJSONTyped(json, false);
}

export function ImportClientsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportClientsDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clients': ((json['clients'] as Array<any>).map(ImportClientDTOFromJSON)),
    };
}

export function ImportClientsDTOToJSON(json: any): ImportClientsDTO {
    return ImportClientsDTOToJSONTyped(json, false);
}

export function ImportClientsDTOToJSONTyped(value?: ImportClientsDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clients': ((value['clients'] as Array<any>).map(ImportClientDTOToJSON)),
    };
}

