/* tslint:disable */
/* eslint-disable */
/**
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportClientDTO
 */
export interface ImportClientDTO {
    /**
     * 
     * @type {string}
     * @memberof ImportClientDTO
     */
    clientEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ImportClientDTO
     */
    clientId: string;
}

/**
 * Check if a given object implements the ImportClientDTO interface.
 */
export function instanceOfImportClientDTO(value: object): value is ImportClientDTO {
    if (!('clientEmail' in value) || value['clientEmail'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function ImportClientDTOFromJSON(json: any): ImportClientDTO {
    return ImportClientDTOFromJSONTyped(json, false);
}

export function ImportClientDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportClientDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clientEmail': json['clientEmail'],
        'clientId': json['clientId'],
    };
}

export function ImportClientDTOToJSON(json: any): ImportClientDTO {
    return ImportClientDTOToJSONTyped(json, false);
}

export function ImportClientDTOToJSONTyped(value?: ImportClientDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientEmail': value['clientEmail'],
        'clientId': value['clientId'],
    };
}

