/*
Futr Enterprise API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
)


// DocumentsAPIService DocumentsAPI service
type DocumentsAPIService service

type ApiDocumentControllerUploadDocumentRequest struct {
	ctx context.Context
	ApiService *DocumentsAPIService
	file *os.File
	monetized *bool
	fileHash *string
	derivedKey *string
	password *string
	isID *bool
	taskId *string
}

func (r ApiDocumentControllerUploadDocumentRequest) File(file *os.File) ApiDocumentControllerUploadDocumentRequest {
	r.file = file
	return r
}

func (r ApiDocumentControllerUploadDocumentRequest) Monetized(monetized bool) ApiDocumentControllerUploadDocumentRequest {
	r.monetized = &monetized
	return r
}

func (r ApiDocumentControllerUploadDocumentRequest) FileHash(fileHash string) ApiDocumentControllerUploadDocumentRequest {
	r.fileHash = &fileHash
	return r
}

// required for end-client use only, enterprise should skip this property
func (r ApiDocumentControllerUploadDocumentRequest) DerivedKey(derivedKey string) ApiDocumentControllerUploadDocumentRequest {
	r.derivedKey = &derivedKey
	return r
}

// user&#39;s decryption password
func (r ApiDocumentControllerUploadDocumentRequest) Password(password string) ApiDocumentControllerUploadDocumentRequest {
	r.password = &password
	return r
}

func (r ApiDocumentControllerUploadDocumentRequest) IsID(isID bool) ApiDocumentControllerUploadDocumentRequest {
	r.isID = &isID
	return r
}

func (r ApiDocumentControllerUploadDocumentRequest) TaskId(taskId string) ApiDocumentControllerUploadDocumentRequest {
	r.taskId = &taskId
	return r
}

func (r ApiDocumentControllerUploadDocumentRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.DocumentControllerUploadDocumentExecute(r)
}

/*
DocumentControllerUploadDocument Uploading a new document

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDocumentControllerUploadDocumentRequest
*/
func (a *DocumentsAPIService) DocumentControllerUploadDocument(ctx context.Context) ApiDocumentControllerUploadDocumentRequest {
	return ApiDocumentControllerUploadDocumentRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return string
func (a *DocumentsAPIService) DocumentControllerUploadDocumentExecute(r ApiDocumentControllerUploadDocumentRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DocumentsAPIService.DocumentControllerUploadDocument")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/documents"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}
	if r.monetized == nil {
		return localVarReturnValue, nil, reportError("monetized is required and must be specified")
	}
	if r.fileHash == nil {
		return localVarReturnValue, nil, reportError("fileHash is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	parameterAddToHeaderOrQuery(localVarFormParams, "monetized", r.monetized, "", "")
	parameterAddToHeaderOrQuery(localVarFormParams, "fileHash", r.fileHash, "", "")
	if r.derivedKey != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "derivedKey", r.derivedKey, "", "")
	}
	if r.password != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "password", r.password, "", "")
	}
	if r.isID != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "isID", r.isID, "", "")
	}
	if r.taskId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "taskId", r.taskId, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
