/*
Futr Enterprise API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthDTO{}

// AuthDTO struct for AuthDTO
type AuthDTO struct {
	ClientId string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

type _AuthDTO AuthDTO

// NewAuthDTO instantiates a new AuthDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthDTO(clientId string, clientSecret string) *AuthDTO {
	this := AuthDTO{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewAuthDTOWithDefaults instantiates a new AuthDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthDTOWithDefaults() *AuthDTO {
	this := AuthDTO{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *AuthDTO) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AuthDTO) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AuthDTO) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AuthDTO) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AuthDTO) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AuthDTO) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o AuthDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecret"] = o.ClientSecret
	return toSerialize, nil
}

func (o *AuthDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clientId",
		"clientSecret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthDTO := _AuthDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthDTO)

	if err != nil {
		return err
	}

	*o = AuthDTO(varAuthDTO)

	return err
}

type NullableAuthDTO struct {
	value *AuthDTO
	isSet bool
}

func (v NullableAuthDTO) Get() *AuthDTO {
	return v.value
}

func (v *NullableAuthDTO) Set(val *AuthDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthDTO(val *AuthDTO) *NullableAuthDTO {
	return &NullableAuthDTO{value: val, isSet: true}
}

func (v NullableAuthDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


