/*
Futr Enterprise API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportClientsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportClientsDTO{}

// ImportClientsDTO struct for ImportClientsDTO
type ImportClientsDTO struct {
	Clients []ImportClientDTO `json:"clients"`
}

type _ImportClientsDTO ImportClientsDTO

// NewImportClientsDTO instantiates a new ImportClientsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportClientsDTO(clients []ImportClientDTO) *ImportClientsDTO {
	this := ImportClientsDTO{}
	this.Clients = clients
	return &this
}

// NewImportClientsDTOWithDefaults instantiates a new ImportClientsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportClientsDTOWithDefaults() *ImportClientsDTO {
	this := ImportClientsDTO{}
	return &this
}

// GetClients returns the Clients field value
func (o *ImportClientsDTO) GetClients() []ImportClientDTO {
	if o == nil {
		var ret []ImportClientDTO
		return ret
	}

	return o.Clients
}

// GetClientsOk returns a tuple with the Clients field value
// and a boolean to check if the value has been set.
func (o *ImportClientsDTO) GetClientsOk() ([]ImportClientDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Clients, true
}

// SetClients sets field value
func (o *ImportClientsDTO) SetClients(v []ImportClientDTO) {
	o.Clients = v
}

func (o ImportClientsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportClientsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clients"] = o.Clients
	return toSerialize, nil
}

func (o *ImportClientsDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clients",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportClientsDTO := _ImportClientsDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportClientsDTO)

	if err != nil {
		return err
	}

	*o = ImportClientsDTO(varImportClientsDTO)

	return err
}

type NullableImportClientsDTO struct {
	value *ImportClientsDTO
	isSet bool
}

func (v NullableImportClientsDTO) Get() *ImportClientsDTO {
	return v.value
}

func (v *NullableImportClientsDTO) Set(val *ImportClientsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableImportClientsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableImportClientsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportClientsDTO(val *ImportClientsDTO) *NullableImportClientsDTO {
	return &NullableImportClientsDTO{value: val, isSet: true}
}

func (v NullableImportClientsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportClientsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


