/*
Futr Enterprise API Documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportClientDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportClientDTO{}

// ImportClientDTO struct for ImportClientDTO
type ImportClientDTO struct {
	ClientEmail string `json:"clientEmail"`
	ClientId string `json:"clientId"`
}

type _ImportClientDTO ImportClientDTO

// NewImportClientDTO instantiates a new ImportClientDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportClientDTO(clientEmail string, clientId string) *ImportClientDTO {
	this := ImportClientDTO{}
	this.ClientEmail = clientEmail
	this.ClientId = clientId
	return &this
}

// NewImportClientDTOWithDefaults instantiates a new ImportClientDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportClientDTOWithDefaults() *ImportClientDTO {
	this := ImportClientDTO{}
	return &this
}

// GetClientEmail returns the ClientEmail field value
func (o *ImportClientDTO) GetClientEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientEmail
}

// GetClientEmailOk returns a tuple with the ClientEmail field value
// and a boolean to check if the value has been set.
func (o *ImportClientDTO) GetClientEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientEmail, true
}

// SetClientEmail sets field value
func (o *ImportClientDTO) SetClientEmail(v string) {
	o.ClientEmail = v
}

// GetClientId returns the ClientId field value
func (o *ImportClientDTO) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *ImportClientDTO) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *ImportClientDTO) SetClientId(v string) {
	o.ClientId = v
}

func (o ImportClientDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportClientDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientEmail"] = o.ClientEmail
	toSerialize["clientId"] = o.ClientId
	return toSerialize, nil
}

func (o *ImportClientDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clientEmail",
		"clientId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportClientDTO := _ImportClientDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportClientDTO)

	if err != nil {
		return err
	}

	*o = ImportClientDTO(varImportClientDTO)

	return err
}

type NullableImportClientDTO struct {
	value *ImportClientDTO
	isSet bool
}

func (v NullableImportClientDTO) Get() *ImportClientDTO {
	return v.value
}

func (v *NullableImportClientDTO) Set(val *ImportClientDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableImportClientDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableImportClientDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportClientDTO(val *ImportClientDTO) *NullableImportClientDTO {
	return &NullableImportClientDTO{value: val, isSet: true}
}

func (v NullableImportClientDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportClientDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


