/*
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DocumentsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DocumentsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DocumentsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for documentControllerUploadDocument
     * @param _file  (required)
     * @param monetized  (required)
     * @param fileHash  (required)
     * @param derivedKey required for end-client use only, enterprise should skip this property (optional)
     * @param password user&#39;s decryption password (optional)
     * @param isID  (optional)
     * @param taskId  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call documentControllerUploadDocumentCall(@javax.annotation.Nonnull File _file, @javax.annotation.Nonnull Boolean monetized, @javax.annotation.Nonnull String fileHash, @javax.annotation.Nullable String derivedKey, @javax.annotation.Nullable String password, @javax.annotation.Nullable Boolean isID, @javax.annotation.Nullable String taskId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/documents";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        if (monetized != null) {
            localVarFormParams.put("monetized", monetized);
        }

        if (fileHash != null) {
            localVarFormParams.put("fileHash", fileHash);
        }

        if (derivedKey != null) {
            localVarFormParams.put("derivedKey", derivedKey);
        }

        if (password != null) {
            localVarFormParams.put("password", password);
        }

        if (isID != null) {
            localVarFormParams.put("isID", isID);
        }

        if (taskId != null) {
            localVarFormParams.put("taskId", taskId);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call documentControllerUploadDocumentValidateBeforeCall(@javax.annotation.Nonnull File _file, @javax.annotation.Nonnull Boolean monetized, @javax.annotation.Nonnull String fileHash, @javax.annotation.Nullable String derivedKey, @javax.annotation.Nullable String password, @javax.annotation.Nullable Boolean isID, @javax.annotation.Nullable String taskId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling documentControllerUploadDocument(Async)");
        }

        // verify the required parameter 'monetized' is set
        if (monetized == null) {
            throw new ApiException("Missing the required parameter 'monetized' when calling documentControllerUploadDocument(Async)");
        }

        // verify the required parameter 'fileHash' is set
        if (fileHash == null) {
            throw new ApiException("Missing the required parameter 'fileHash' when calling documentControllerUploadDocument(Async)");
        }

        return documentControllerUploadDocumentCall(_file, monetized, fileHash, derivedKey, password, isID, taskId, _callback);

    }

    /**
     * Uploading a new document
     * 
     * @param _file  (required)
     * @param monetized  (required)
     * @param fileHash  (required)
     * @param derivedKey required for end-client use only, enterprise should skip this property (optional)
     * @param password user&#39;s decryption password (optional)
     * @param isID  (optional)
     * @param taskId  (optional)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public String documentControllerUploadDocument(@javax.annotation.Nonnull File _file, @javax.annotation.Nonnull Boolean monetized, @javax.annotation.Nonnull String fileHash, @javax.annotation.Nullable String derivedKey, @javax.annotation.Nullable String password, @javax.annotation.Nullable Boolean isID, @javax.annotation.Nullable String taskId) throws ApiException {
        ApiResponse<String> localVarResp = documentControllerUploadDocumentWithHttpInfo(_file, monetized, fileHash, derivedKey, password, isID, taskId);
        return localVarResp.getData();
    }

    /**
     * Uploading a new document
     * 
     * @param _file  (required)
     * @param monetized  (required)
     * @param fileHash  (required)
     * @param derivedKey required for end-client use only, enterprise should skip this property (optional)
     * @param password user&#39;s decryption password (optional)
     * @param isID  (optional)
     * @param taskId  (optional)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> documentControllerUploadDocumentWithHttpInfo(@javax.annotation.Nonnull File _file, @javax.annotation.Nonnull Boolean monetized, @javax.annotation.Nonnull String fileHash, @javax.annotation.Nullable String derivedKey, @javax.annotation.Nullable String password, @javax.annotation.Nullable Boolean isID, @javax.annotation.Nullable String taskId) throws ApiException {
        okhttp3.Call localVarCall = documentControllerUploadDocumentValidateBeforeCall(_file, monetized, fileHash, derivedKey, password, isID, taskId, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Uploading a new document (asynchronously)
     * 
     * @param _file  (required)
     * @param monetized  (required)
     * @param fileHash  (required)
     * @param derivedKey required for end-client use only, enterprise should skip this property (optional)
     * @param password user&#39;s decryption password (optional)
     * @param isID  (optional)
     * @param taskId  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call documentControllerUploadDocumentAsync(@javax.annotation.Nonnull File _file, @javax.annotation.Nonnull Boolean monetized, @javax.annotation.Nonnull String fileHash, @javax.annotation.Nullable String derivedKey, @javax.annotation.Nullable String password, @javax.annotation.Nullable Boolean isID, @javax.annotation.Nullable String taskId, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = documentControllerUploadDocumentValidateBeforeCall(_file, monetized, fileHash, derivedKey, password, isID, taskId, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
