/*
 * Futr Enterprise API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AuthDTO;
import org.openapitools.client.model.ImportClientsDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EnterpriseApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public EnterpriseApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EnterpriseApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for enterpriseControllerAuth
     * @param authDTO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully authenticated. Access token returned with doc/upload scope. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials provided. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enterpriseControllerAuthCall(@javax.annotation.Nonnull AuthDTO authDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = authDTO;

        // create path and map variables
        String localVarPath = "/enterprise/auth";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call enterpriseControllerAuthValidateBeforeCall(@javax.annotation.Nonnull AuthDTO authDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authDTO' is set
        if (authDTO == null) {
            throw new ApiException("Missing the required parameter 'authDTO' when calling enterpriseControllerAuth(Async)");
        }

        return enterpriseControllerAuthCall(authDTO, _callback);

    }

    /**
     * Authenticate and retrieve OAuth2 token
     * Exchanges your enterprise client credentials for an OAuth2 access token. This token is required for accessing protected enterprise endpoints including import-clients and document operations. 
     * @param authDTO  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully authenticated. Access token returned with doc/upload scope. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials provided. </td><td>  -  </td></tr>
     </table>
     */
    public Object enterpriseControllerAuth(@javax.annotation.Nonnull AuthDTO authDTO) throws ApiException {
        ApiResponse<Object> localVarResp = enterpriseControllerAuthWithHttpInfo(authDTO);
        return localVarResp.getData();
    }

    /**
     * Authenticate and retrieve OAuth2 token
     * Exchanges your enterprise client credentials for an OAuth2 access token. This token is required for accessing protected enterprise endpoints including import-clients and document operations. 
     * @param authDTO  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully authenticated. Access token returned with doc/upload scope. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials provided. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> enterpriseControllerAuthWithHttpInfo(@javax.annotation.Nonnull AuthDTO authDTO) throws ApiException {
        okhttp3.Call localVarCall = enterpriseControllerAuthValidateBeforeCall(authDTO, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Authenticate and retrieve OAuth2 token (asynchronously)
     * Exchanges your enterprise client credentials for an OAuth2 access token. This token is required for accessing protected enterprise endpoints including import-clients and document operations. 
     * @param authDTO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully authenticated. Access token returned with doc/upload scope. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials provided. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enterpriseControllerAuthAsync(@javax.annotation.Nonnull AuthDTO authDTO, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = enterpriseControllerAuthValidateBeforeCall(authDTO, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for enterpriseControllerImportClients
     * @param importClientsDTO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Clients successfully imported. Returns an empty response body. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body. Ensure clients array has at least 1 item and all fields are valid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. Invalid or missing OAuth2 token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. Your organization does not have enterprise access. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enterpriseControllerImportClientsCall(@javax.annotation.Nonnull ImportClientsDTO importClientsDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = importClientsDTO;

        // create path and map variables
        String localVarPath = "/enterprise/import-clients";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call enterpriseControllerImportClientsValidateBeforeCall(@javax.annotation.Nonnull ImportClientsDTO importClientsDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'importClientsDTO' is set
        if (importClientsDTO == null) {
            throw new ApiException("Missing the required parameter 'importClientsDTO' when calling enterpriseControllerImportClients(Async)");
        }

        return enterpriseControllerImportClientsCall(importClientsDTO, _callback);

    }

    /**
     * Import enterprise clients
     * Imports a list of clients into your organization. Requires a valid OAuth2 access token obtained from the /auth endpoint. Each client will be added to your organization with the provided email and unique external client ID.  The clientId will serve as an external identifier to track which enterprise client each consumer belongs to. Critically, this clientId mapping determines document upload behavior: documents uploaded by imported clients will be stored unencrypted (enterprise-managed storage). Clients will be created in Cognito if they do not already exist, and their association with your organization and the provided clientId will be stored in the system.  Import Format: A customer-generated CSV file will be used to onboard multiple users in bulk. The CSV file will have the following format:  clientEmail,clientId  When using the Brands App, the user&#39;s email will be used as the clientEmail and the initial password will be an OTP sent to the user&#39;s email. The clientId will be any unique identifier from your enterprise system that you want to associate with this client. This will allow you to maintain a mapping between your enterprise system and the consumers created in this platform, and will enable unencrypted document storage for these clients.  
     * @param importClientsDTO  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Clients successfully imported. Returns an empty response body. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body. Ensure clients array has at least 1 item and all fields are valid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. Invalid or missing OAuth2 token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. Your organization does not have enterprise access. </td><td>  -  </td></tr>
     </table>
     */
    public Object enterpriseControllerImportClients(@javax.annotation.Nonnull ImportClientsDTO importClientsDTO) throws ApiException {
        ApiResponse<Object> localVarResp = enterpriseControllerImportClientsWithHttpInfo(importClientsDTO);
        return localVarResp.getData();
    }

    /**
     * Import enterprise clients
     * Imports a list of clients into your organization. Requires a valid OAuth2 access token obtained from the /auth endpoint. Each client will be added to your organization with the provided email and unique external client ID.  The clientId will serve as an external identifier to track which enterprise client each consumer belongs to. Critically, this clientId mapping determines document upload behavior: documents uploaded by imported clients will be stored unencrypted (enterprise-managed storage). Clients will be created in Cognito if they do not already exist, and their association with your organization and the provided clientId will be stored in the system.  Import Format: A customer-generated CSV file will be used to onboard multiple users in bulk. The CSV file will have the following format:  clientEmail,clientId  When using the Brands App, the user&#39;s email will be used as the clientEmail and the initial password will be an OTP sent to the user&#39;s email. The clientId will be any unique identifier from your enterprise system that you want to associate with this client. This will allow you to maintain a mapping between your enterprise system and the consumers created in this platform, and will enable unencrypted document storage for these clients.  
     * @param importClientsDTO  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Clients successfully imported. Returns an empty response body. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body. Ensure clients array has at least 1 item and all fields are valid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. Invalid or missing OAuth2 token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. Your organization does not have enterprise access. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> enterpriseControllerImportClientsWithHttpInfo(@javax.annotation.Nonnull ImportClientsDTO importClientsDTO) throws ApiException {
        okhttp3.Call localVarCall = enterpriseControllerImportClientsValidateBeforeCall(importClientsDTO, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Import enterprise clients (asynchronously)
     * Imports a list of clients into your organization. Requires a valid OAuth2 access token obtained from the /auth endpoint. Each client will be added to your organization with the provided email and unique external client ID.  The clientId will serve as an external identifier to track which enterprise client each consumer belongs to. Critically, this clientId mapping determines document upload behavior: documents uploaded by imported clients will be stored unencrypted (enterprise-managed storage). Clients will be created in Cognito if they do not already exist, and their association with your organization and the provided clientId will be stored in the system.  Import Format: A customer-generated CSV file will be used to onboard multiple users in bulk. The CSV file will have the following format:  clientEmail,clientId  When using the Brands App, the user&#39;s email will be used as the clientEmail and the initial password will be an OTP sent to the user&#39;s email. The clientId will be any unique identifier from your enterprise system that you want to associate with this client. This will allow you to maintain a mapping between your enterprise system and the consumers created in this platform, and will enable unencrypted document storage for these clients.  
     * @param importClientsDTO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Clients successfully imported. Returns an empty response body. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body. Ensure clients array has at least 1 item and all fields are valid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. Invalid or missing OAuth2 token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. Your organization does not have enterprise access. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enterpriseControllerImportClientsAsync(@javax.annotation.Nonnull ImportClientsDTO importClientsDTO, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = enterpriseControllerImportClientsValidateBeforeCall(importClientsDTO, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
